name: Execute Script
on:
  push:
    branches:
      - main
jobs:
  example-job:
   runs-on: self-hosted
   environment: 'linux'
   steps:
     - name: Run build script
       shell: bash
       id: execute-script
       continue-on-error: true
       run: sh /home/bandaru/Pictures/myfiles/first.sh
  example-job1:
   runs-on: self-hosted
   steps:
     - name: Run build script
       shell: bash
       id: execute-script
       continue-on-error: true
       run: sh /home/bandaru/Pictures/myfiles/second.sh       
       
