name: Execute Script
on:
  push:
    branches:
      - main
jobs:
  example-job:
   runs-on: self-hosted
   steps:
     - name: Run build script
       shell: bash
       id: execute-script
       continue-on-error: true
       run: sh /home/bandaru/Pictures/myfiles/first.sh
               
         echo "::set-output name=exit-code::$?"

     - name: Take action based on exit codes
       if: ${{ steps.execute-script.outputs.exit-code == '0' }}
       run: echo "Script succeeded"
     - name: Notify on failure
       if: ${{ steps.execute-script.outputs.exit-code != '0' }}
       run: echo "Script failed"
