name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: self-hosted
    container:
      image: nginx
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: ls 
